### PR TITLE
add module dependency on sockets

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by bwoebi** [comment]
ext/sockets is a soft dependency - it needs one symbol from ext/socket when it's loaded, but ext/uv should also work without ext/sockets loaded.

**Comment by remicollet** [comment]
```
$ php -n -d extension=modules/uv.so -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/uv.so' - modules/uv.so: undefined symbol: php_sockets_le_socket in Unknown on line 0
```

Perhaps this can work on some build using the default RTLD_LAZY option (dlopen), but most linux distro use RTLD_NOW for security reason.

**Comment by bwoebi** [comment]
@remicollet So, I guess ZEND_MOD_OPTIONAL() would be correct?

**Comment by bwoebi** [comment]
http://lxr.php.net/source/xref/PHP-7.0/Zend/zend_portability.h#140

Shows that we are actually using RTLD_LAZY?

**Comment by bwoebi** [comment]
@remicollet This last change is for guaranteeing loading order and such?

**Comment by remicollet** [comment]
> Shows that we are actually using RTLD_LAZY?

Indeed, as I said "build using the default RTLD_LAZY option (dlopen), but most linux distro use RTLD_NOW"

> So, I guess ZEND_MOD_OPTIONAL() would be correct?

No, see second commit, which seems ok for me (only dep when HAVE_SOCKET, so when the dl_fetch_symbol is not used)

**Comment by remicollet** [comment]
BTW, when you have a shared sockets extension you have (main/php_config.h)
```
#define HAVE_SOCKET 1
#define COMPILE_DL_SOCKETS 1
```

**Comment by bwoebi** [comment]
Oh, distros are changing the value inside the source code. Sigh. Got it.

So, I shall write `defined(HAVE_SOCKET) && !defined(COMPILE_DL_SOCKETS)` instead?

Though, I wonder whether we do actually need then:
```C
#else
ZEND_MOD_OPTIONAL("sockets")
```
To ensure proper loading order?

**Comment by remicollet** [comment]
ZEND_MOD_REQUIRED or ZEND_MOD_OPTIONAL doesn't ensure load order, but only MINIT call order.

* Load order is not a problem on default build (thanks to RTLD_LAZY)
* Load order is managed (when RTLD_NOW is used) in downstream by numerical prefix for ini files  (e.g. 20-sockets.ini and 40-uv.ini)

**Comment by bwoebi** [comment]
Ah okay. But still, is there a reason why your patch instead of:

`defined(HAVE_SOCKET) && !defined(COMPILE_DL_SOCKETS)` (everywhere where we currently have `defined(HAVE_SOCKET)` right now)?

**Comment by remicollet** [comment]
chicken and egg issue... :(

```
#ifdef HAVE_SOCKETS
#include "ext/sockets/php_sockets.h"
```
Above test is correct for checking php_sockets.h exists (so all other tests should use the same logic, at least "php_sockets_le_socket" declaration... so also its usage)

So IMHO, simpler way, when HAVE_SOCKETS, make it "required" ;)
(and clean the dl_fetch_symbol stuff...)

Or keep it as you prefer (but downstream will probably have to patch your code to clean this part)

**Comment by remicollet** [comment]
Closing, as this not really the right solution.

**Comment by bwoebi** [comment]
I've tested it, `!defined(COMPILE_DL_SOCKETS)` fixes it perfectly, also using your php distribution. Pushing that shortly.

**Pull request closed without merging**
